### PR TITLE
Updated tom toolkit to latest version, added tom_tns, and integrated …

### PR DESCRIPTION
**Pull request by jnation3406**
…hermes and tns sharing to photometry and spectroscopy

Curtis feel free to add anyone else as a reviewer that is working on SNEX2. I've run this locally with the clone of the SNEX2 database you gave me and have submitted old targets with photometry/spectroscopy to hermes-dev, but it may still need some work to integrate it into your running snex instance and test things.

### CODE REVIEW

**Comment by crpellegrino** [comment]
I took this opportunity to merge in some changes I had made to improve data upload capabilities for SNEx2 users. This will help to test this PR locally by improving the process of manually uploading spectra data files.

Before testing you'll have to update your local `tomtoolkit` and `tom_nonlocalizedevents` versions to the versions pinned in `requirements.txt`. To test, I uploaded a spectrum ascii/fits file (one that I downloaded straight from SNEx1) using the forms on the target detail page, then tested the "Open in Hermes" sharing option under the "Spectroscopy" tab on the same target page.

As far as I can tell, a few things have to be added/double checked on the SNEx2 side before deploying, namely:
1. The new HERMES environment variables have to be added to the SNEx2 docker
2. Make sure the `sync_databases.py` script is working with the newly added spectra data products 
3. Make sure the button to submit a classification report to TNS is working in SNEx2 (make sure SNEx2 has the right TNS credentials)

**Comment by jnation3406** [comment]
Also note, for your SNEX2 hermes account (which you will have the API token for in your SNEX2 settings.py / env variable), you should log into that account on Hermes (both dev and prod separately if you will use both), and go to the user profile page and add in your TNS bot credentials. That way, when you submit to TNS through hermes through the TOM, it will use your TNS bot credentials to submit rather than the default hermes bot credentials.

**Comment by jnation3406** [comment]
And one last note - Hermes sharing requires certain fields in your reduced datums that might not be present in your data. The TOM team had me remove the default settings options to fill in those fields for you automatically since it could be misleading, so you will need to manually add those fields to your data if you want to be able to single-click share with hermes. For instance, datums need either a `telescope` or `instrument` set. You can always open the data in the Hermes UI though and add the missing fields there before sharing.

**Comment by jrfarah** [comment]
@crpellegrino on my bare metal installation the data upload is not working. I install and setup from @jnation3406 's branch, but when I attempt to upload a spectrum I get the following error:

` There was a problem processing your file: M31_nova/none/spectrum_reduced-craig_2022-05-17.txt `

image

This happened with `.ascii` and `.txt` spectra.

**Comment by crpellegrino** [comment]
Based on that screenshot I'm pretty sure you didn't pull the changes I made to the data upload. Make sure you're checking out and pulling from [this](https://github.com/LCOGT/snex2/tree/feature/add_hermes_tns_sharing) branch. The attached screenshot shows what the "Manage Data" tab should look like with the new changes I made. 

image

**Comment by jrfarah** [comment]
Thanks @crpellegrino , I was able to get this branch installed and tested. Data upload is working and the HERMES/TNS functionality appears to be as well.

**Pull request merged**
